title: k4vahk
description: Aprendiz de ciberseguridad documentando su camino
url: "https://k4vahk.github.io"
author: Kava

# Tema — lo desactivamos para usar diseño propio
theme: null

# Colecciones personalizadas
collections:
  writeups:
    output: true
    permalink: /writeups/:name/
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Plugins
plugins:
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title/